s|^const dirs = \[.*\];|const dirs = ['MEMORY', 'MEMORY/ACTIVE-BUFFER', 'MEMORY/ENDED-BUFFER', 'MEMORY/PROJECTS', 'MEMORY/SKILLS'];|
s|^  'USER.MD':|  'MEMORY/USER.MD':|
s|^  'PREFERENCE.MD':|  'MEMORY/PREFERENCE.MD':|
s|^  'PATTERNS.MD':|  'MEMORY/PATTERNS.MD':|
